### ISSUE TITLE
Issue with a pair of double quotes representing blank field

### ISSUE THREAD

**Issue by JavaScriptDude** [maxogden/csv-spectrum#12]
In my experience, two concurrent double quotes should only be used in a CSV file to escape a single double quote in a data record and such a data record needs to be encapsulated with a pair of double quotes. A pair of double quotes should never be used to express a blank field as it is redundant.

See section 9.3 in http://mastpoint.curzonnassau.com/csv-1203/csv-1203.pdf for a definition of this ideal.

By presenting a pair of double quotes to represent blank text in a CSV is throws a spin on parsers that try to conform to the most common way that CSV files are written which closely resembles what the 'standard' csv-1203 is trying to illustrate. For instance, Excel will never write this.

Therefore, IMO the tests for 'deepEqual' and 'empty_crlf' are both non-conformant to common standards to and should be avoided for csv parsers that follow strict csv rules. 

Maybe you could consider adding "strict" versus "loose" in your test definitions?

**Comment by maxogden** [comment]
I try and conform to https://tools.ietf.org/html/rfc4180 which states `Each field may or may not be enclosed in double quotes (however some programs, such as Microsoft Excel, do not use double quotes at all).` (e.g. they are optional).

**Comment by JavaScriptDude** [comment]
Understood. I have read the portion of rfc4180. Makes sense to have the parser handle those edge cases effectively. Closing the issue.
